version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '5000:5000' 
    volumes:
      - ./backend:/app
    command: pnpm run dev
    depends_on:
      - client
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - '3000:3000' 
    volumes:
      - ./client:/app
    command: npm run dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
